default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "AsakusaSatellite.xcodeproj")
    build_app(workspace: "AsakusaSatellite.xcworkspace", scheme: "AsakusaSatellite")
    commit_version_bump
    add_git_tag(tag: "#{get_version_number(target: "AsakusaSatellite")}-#{get_build_number}")
    push_git_tags
    upload_to_testflight
  end
end
